version: '3'

services:
  tp_dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: tp_dashboard:3
    ports: 
      - '8080:80'
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - ~/.aws/:/root/.aws:ro
