version: '3'
services:
  web:
    image: ${image}
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: dashboard-ecs
        awslogs-region: ${REGION}
        awslogs-stream-prefix: web
        